# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build & Deploy - pozworld-streaming

concurrency: 
  group: pozworld-streaming
  cancel-in-progress: true

on:
  push:
    branches:
      - poz.world
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - uses: ./.github/actions/build-and-push-docker-image
      with:
        git-token: ${{ secrets.HIVCHASER_PACKAGES_PAT }}
        github-password: ${{ secrets.HIVCHASER_PACKAGES_PAT }}
        username: hivchaser
        acr-password: ${{ secrets.AZURECR_KEY }}
        tag: |
          ghcr.io/poz-world/streaming.poz.world
          thebackroomlife.azurecr.io/streaming.poz.world
        tag-prefix: pwv
        description: Streaming server for your self-hosted social media platform for the HIV community
        dockerfile: Dockerfile.streaming.poz.world

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'pozworld-streaming'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_be5f76a6413349b08fc0dae02bab8183 }}
        images: 'ghcr.io/poz-world/streaming.poz.world:${{ github.sha }}'
